"""Admin commands.

  uv run migrate                         apply database migrations (app tables)
  uv run seed                            demo users + starter glossary/examples
  uv run create-user NAME ROLE [--salesman "Salesman 12"] [--password X]
  uv run bootstrap                       everything, in order, for a fresh machine
"""

import argparse
import secrets

from alembic import command
from alembic.config import Config
from sqlalchemy import select

from querynest.config import BACKEND_DIR, ENV_FILE, settings
from querynest.permissions import ROLES

DEMO_USERS = [
    # username, display name, role, attributes
    ("admin", "Admin", "admin", {}),
    ("manager", "Sales Manager", "manager", {}),
    ("finance", "Finance Team", "finance", {}),
    ("sales12", "Salesman 12", "sales", {"salesman": "Salesman 12"}),
]


def migrate() -> None:
    cfg = Config(str(BACKEND_DIR / "alembic.ini"))
    command.upgrade(cfg, "head")
    print("Migrations applied.")


def upsert_user(username: str, role: str, password: str, display_name: str = "",
                attributes: dict | None = None) -> bool:
    from querynest.appdb import User, session
    from querynest.auth import hash_password

    if role not in ROLES:
        raise SystemExit(f"Unknown role '{role}'. Roles: {list(ROLES)}")
    with session() as s:
        user = s.scalars(select(User).where(User.username == username)).first()
        created = user is None
        if created:
            user = User(username=username)
            s.add(user)
        user.display_name = display_name or username
        user.role = role
        user.attributes = attributes or {}
        user.password_hash = hash_password(password)
        s.commit()
    return created


def demo_password() -> str:
    if settings.demo_password is not None:
        return settings.demo_password.get_secret_value()
    password = secrets.token_urlsafe(12)
    with ENV_FILE.open("a", encoding="utf-8") as f:
        f.write(f"\n# Password of the demo users (generated by `uv run seed`)\nDEMO_PASSWORD={password}\n")
    return password


def seed() -> None:
    from querynest import knowledge

    password = demo_password()
    for username, name, role, attributes in DEMO_USERS:
        upsert_user(username, role, password, name, attributes)
    terms, examples = knowledge.seed()
    print(f"Demo users: {', '.join(u[0] for u in DEMO_USERS)} (password: DEMO_PASSWORD in {ENV_FILE.name})")
    print(f"Knowledge: {terms} glossary terms and {examples} curated examples added")


def create_user() -> None:
    p = argparse.ArgumentParser(prog="create-user")
    p.add_argument("username")
    p.add_argument("role", choices=list(ROLES))
    p.add_argument("--name", default="")
    p.add_argument("--salesman", help="row filter value for the sales role, e.g. 'Salesman 12'")
    p.add_argument("--password", help="default: a random one, printed once")
    a = p.parse_args()
    password = a.password or secrets.token_urlsafe(12)
    attributes = {"salesman": a.salesman} if a.salesman else {}
    created = upsert_user(a.username, a.role, password, a.name, attributes)
    print(f"{'Created' if created else 'Updated'} {a.username} ({a.role}).",
          "" if a.password else f"Password: {password}")


def make_templates() -> None:
    """Author the Excel report templates with a real PivotTable (needs Windows + Excel)."""
    import sys

    from querynest.db import fetch_all
    from querynest.guardrails import validate_sql
    from querynest.permissions import system_user
    from querynest.report_templates import load_templates
    from querynest.results import column_types

    from querynest.db import close_pool
    from querynest.report_templates import author_template

    wanted = sys.argv[1:]
    admin = system_user("admin")
    try:
        for name, template in load_templates().items():
            if wanted and name not in wanted:
                continue
            # Only the column names and types are needed: 5 rows are read to detect the types,
            # but only placeholder values are written into the template file.
            data = fetch_all(validate_sql(template.sql, admin, max_rows=5).sql, None, admin)
            author_template(template, data["columns"], column_types(data["columns"], data["rows"]))
            print(f"Authored {template.path.name}: columns {data['columns']}")
    finally:
        close_pool()


def bootstrap() -> None:
    from querynest import load_excel, setup_db

    print("== 1/4 Load Excel into Postgres"); load_excel.main()
    print("== 2/4 Database roles and permissions"); setup_db.main()
    # setup-db may have just written new secrets to .env: reload settings for the next steps
    settings.__init__()
    print("== 3/4 Migrations"); migrate()
    print("== 4/4 Seed"); seed()
