"""Create/sync all database logins, roles and permissions, then prove they work.

Run:  uv run setup-db      (safe to run again at any time; re-run after editing permissions.py)

Roles created:
  agent_reader   LOGIN  the agent's connection. Has NO data rights of its own; it can only
                        SET ROLE to one of the qn_* group roles below, per query.
  qn_<role>      group  one per app role in permissions.py: table/column GRANTs + row policies.
  querynest_app  LOGIN  the API's own tables (schema "app"); cannot read sales data.

This is our strongest safety layer: even if every Python check had a bug, Postgres itself
refuses writes, hidden tables, hidden columns and other people's rows.
"""

import secrets

import psycopg
from psycopg import sql

from querynest.config import ENV_FILE, settings
from querynest.permissions import ROLES, pg_role

SCHEMA = "sales"
APP_SCHEMA = "app"


def ensure_secret(name: str, current, comment: str) -> str:
    """Return the secret from .env, or generate a strong one and append it to .env."""
    if current is not None:
        return current.get_secret_value()
    value = secrets.token_urlsafe(32)
    with ENV_FILE.open("a", encoding="utf-8") as f:
        f.write(f"\n# {comment} (generated by `uv run setup-db`)\n{name}={value}\n")
    print(f"  Generated {name} and saved it to {ENV_FILE.name}")
    return value


def q(statement: str, **names) -> sql.Composed:
    """Build SQL with safely quoted identifiers: q('GRANT ... TO {role}', role='x')."""
    return sql.SQL(statement).format(**{k: sql.Identifier(v) if isinstance(v, str) else v
                                        for k, v in names.items()})


def upsert_login(conn, role: str, password: str) -> None:
    exists = conn.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", [role]).fetchone()
    verb = "ALTER" if exists else "CREATE"
    conn.execute(sql.SQL(verb + " ROLE {} LOGIN PASSWORD {}").format(sql.Identifier(role), sql.Literal(password)))


def roles_exist(conn) -> bool:
    return all(conn.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", [pg_role(r)]).fetchone() for r in ROLES)


def sync_data_permissions(conn) -> None:
    """GRANTs and row-level-security policies on the sales tables, from permissions.ROLES.
    Also called by load-excel, because recreating a table drops its grants and policies."""
    tables = [r[0] for r in conn.execute(
        "SELECT table_name FROM information_schema.tables WHERE table_schema = %s", [SCHEMA])]
    for app_role, role_def in ROLES.items():
        group = pg_role(app_role)
        conn.execute(q("GRANT USAGE ON SCHEMA {s} TO {g}", s=SCHEMA, g=group))
        for table in tables:
            full = f"{SCHEMA}.{table}"
            # Revoking at table level also revokes column-level grants: a clean slate each run
            conn.execute(q("REVOKE ALL ON {t} FROM {g}", t=sql.Identifier(SCHEMA, table), g=group))
            rule = role_def.tables.get(full)
            if rule is None:
                continue  # table invisible to this role
            if rule.denied_columns:
                cols = [r[0] for r in conn.execute(
                    "SELECT column_name FROM information_schema.columns WHERE table_schema=%s AND table_name=%s "
                    "ORDER BY ordinal_position", [SCHEMA, table]) if r[0] not in rule.denied_columns]
                conn.execute(sql.SQL("GRANT SELECT ({}) ON {} TO {}").format(
                    sql.SQL(", ").join(map(sql.Identifier, cols)), sql.Identifier(SCHEMA, table), sql.Identifier(group)))
            else:
                conn.execute(q("GRANT SELECT ON {t} TO {g}", t=sql.Identifier(SCHEMA, table), g=group))

    # Row-level security: with RLS on, a role sees only rows some policy allows it to see
    for table in tables:
        ident = sql.Identifier(SCHEMA, table)
        conn.execute(sql.SQL("ALTER TABLE {} ENABLE ROW LEVEL SECURITY").format(ident))
        for (policy,) in conn.execute("SELECT policyname FROM pg_policies WHERE schemaname=%s AND tablename=%s "
                                      "AND policyname LIKE 'qn\\_%%'", [SCHEMA, table]).fetchall():
            conn.execute(sql.SQL("DROP POLICY {} ON {}").format(sql.Identifier(policy), ident))
        for app_role, role_def in ROLES.items():
            rule = role_def.tables.get(f"{SCHEMA}.{table}")
            if rule is None:
                continue
            if rule.row_filter:
                column, attribute = rule.row_filter
                using = sql.SQL("{} = current_setting({}, true)").format(
                    sql.Identifier(column), sql.Literal(f"querynest.{attribute}"))
            else:
                using = sql.SQL("true")
            conn.execute(sql.SQL("CREATE POLICY {} ON {} FOR SELECT TO {} USING ({})").format(
                sql.Identifier(f"qn_{app_role}_{table}"), ident, sql.Identifier(pg_role(app_role)), using))


def setup(agent_password: str, app_password: str) -> None:
    agent = settings.agent_db_user
    with psycopg.connect(**settings.postgres_conninfo()) as conn:
        # --- the agent's login: read-only, time-limited, no rights of its own
        upsert_login(conn, agent, agent_password)
        conn.execute(q("ALTER ROLE {r} SET default_transaction_read_only = on", r=agent))
        conn.execute(q("ALTER ROLE {r} SET statement_timeout = {t}", r=agent, t=sql.Literal(settings.statement_timeout_ms)))
        conn.execute(q("ALTER ROLE {r} CONNECTION LIMIT 20", r=agent))
        conn.execute(q("GRANT CONNECT ON DATABASE {db} TO {r}", db=settings.postgres_db, r=agent))
        conn.execute(q("CREATE SCHEMA IF NOT EXISTS {s}", s=SCHEMA))
        # Remove the direct rights agent_reader had in Milestones 1-2 (now it must SET ROLE)
        conn.execute(q("REVOKE ALL ON ALL TABLES IN SCHEMA {s} FROM {r}", s=SCHEMA, r=agent))
        conn.execute(q("REVOKE USAGE ON SCHEMA {s} FROM {r}", s=SCHEMA, r=agent))
        conn.execute(q("ALTER DEFAULT PRIVILEGES FOR ROLE {o} IN SCHEMA {s} REVOKE SELECT ON TABLES FROM {r}",
                       o=settings.postgres_user, s=SCHEMA, r=agent))

        # --- one group role per app role; agent_reader may SET ROLE to them but doesn't inherit
        for app_role in ROLES:
            group = pg_role(app_role)
            if not conn.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", [group]).fetchone():
                conn.execute(q("CREATE ROLE {g} NOLOGIN", g=group))
            conn.execute(q("GRANT {g} TO {r} WITH INHERIT FALSE, SET TRUE", g=group, r=agent))
        sync_data_permissions(conn)

        # --- the API's login and its private schema
        upsert_login(conn, settings.app_db_user, app_password)
        conn.execute(q("GRANT CONNECT ON DATABASE {db} TO {r}", db=settings.postgres_db, r=settings.app_db_user))
        conn.execute(q("CREATE SCHEMA IF NOT EXISTS {s} AUTHORIZATION {r}", s=APP_SCHEMA, r=settings.app_db_user))
        conn.execute(q("REVOKE ALL ON SCHEMA {s} FROM PUBLIC", s=APP_SCHEMA))
    print(f"  Roles synced: {agent} -> {[pg_role(r) for r in ROLES]}; {settings.app_db_user} owns schema '{APP_SCHEMA}'")


def self_test(agent_password: str) -> None:
    """Log in AS agent_reader and check each role's view of the data."""
    info = {**settings.postgres_conninfo(), "user": settings.agent_db_user, "password": agent_password}
    checks = [
        # (role, salesman attribute, query, expectation)
        ("-", None, f"SELECT count(*) FROM {SCHEMA}.invoices", "fail"),  # no role: no rights
        ("manager", None, f"SELECT count(*) FROM {SCHEMA}.invoices", "rows"),
        ("manager", None, f"DELETE FROM {SCHEMA}.invoices", "fail"),
        ("manager", None, f"SELECT count(*) FROM {APP_SCHEMA}.users", "fail"),
        ("sales", None, f"SELECT count(*) FROM {SCHEMA}.account_entries", "fail"),
        ("sales", None, f"SELECT costvalue FROM {SCHEMA}.invoices", "fail"),
        ("sales", None, f"SELECT count(*) FROM {SCHEMA}.invoices", "zero"),  # no salesman set: no rows
        ("sales", "Salesman 12", f"SELECT count(DISTINCT salesmna) FROM {SCHEMA}.invoices", "one"),
    ]
    with psycopg.connect(**info, autocommit=True) as conn:
        for role, salesman, query, expect in checks:
            try:
                with conn.transaction():
                    if role != "-":
                        conn.execute(q("SET LOCAL ROLE {g}", g=pg_role(role)))
                    if salesman:
                        conn.execute("SELECT set_config('querynest.salesman', %s, true)", [salesman])
                    value = conn.execute(query).fetchone()[0]
                ok = {"rows": value > 0, "fail": False, "zero": value == 0, "one": value == 1}[expect]
                outcome = f"allowed, result {value}"
            except psycopg.Error as e:
                ok, outcome = expect == "fail", f"refused ({e.diag.message_primary})"
            who = role + (f" ({salesman})" if salesman else "")
            print(f"  [{'PASS' if ok else 'FAIL'}] {who:22} {query}: {outcome}")
            if not ok:
                raise SystemExit("Self-test failed: database permissions are wrong!")


def main() -> None:
    print(f"Setting up database roles on {settings.postgres_db} ...")
    agent_password = ensure_secret("AGENT_DB_PASSWORD", settings.agent_db_password, "Read-only DB login for the agent")
    app_password = ensure_secret("APP_DB_PASSWORD", settings.app_db_password, "DB login for the API's own tables")
    ensure_secret("JWT_SECRET", settings.jwt_secret, "Signs login tokens")
    setup(agent_password, app_password)
    print("Self-test, logged in as the agent:")
    self_test(agent_password)
    print("Done.")


if __name__ == "__main__":
    main()
